wording fix
marijuanARM/futurerestore pull request #55
Opened 2022-02-02 21:16 UTC by verygenericname

2022-02-02 21:34 UTC, Cryptiiiic commented
Any other typos?

2022-02-02 21:34 UTC, verygenericname commented
that's all I saw for now

2022-02-03 02:12 UTC, verygenericname commented
that's all i could find

2022-02-18 17:32 UTC, nyuszika7h commented on futurerestore/futurerestore.cpp
> +
<img src="https://cdn.discordapp.com/emojis/792934328236638267.png?v=1" width="48"></img>

2022-02-19 07:13 UTC, m1stadev requested changes
consistency

2022-02-19 07:13 UTC, m1stadev commented on futurerestore/futurerestore.cpp
> +        printf("Verified ECID in APTicket matches the device ECID\n");
```suggestion
        printf("Verified ECID in APTicket matches the device's ECID\n");

2022-02-19 07:13 UTC, m1stadev commented on futurerestore/futurerestore.cpp
> +            error("ECID inside APTicket doesn't match device ECID\n");
```suggestion
            error("ECID inside APTicket doesn't match the device's ECID\n");

2022-02-19 15:31 UTC, m1stadev approved these changes

2022-03-03 00:56 UTC, Cryptiiiic commented
@verygenericname fix conflicts

2022-03-15 22:13 UTC, verygenericname commented
laziness is fun, i'm just gonna make a new pr cuz why not

2022-03-15 22:45 UTC, Cryptiiiic commented
please add the spacing back and the end file newline

2022-03-20 06:33 UTC, Cryptiiiic commented
bump

2022-03-20 13:25 UTC, closed without merging